# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f190a0e1c0a98ab5327a313d128e5cdfc05fe8e2b7e80d64c65732d073dfe881fd102126da29d28b636ca4de1c8f9b77f9b54200264e96471eb3d0bef013c7a5

test:
  secret_key_base: 0f95cb04ef053037d8d820edf134b008e6715178d370c64612075b34f498af5194563f828b5e75b26270a7efbd5fd1db82e4bc6bd0678a2c3f82cedf25663aa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
